name: comptest
 
on:
  push:
    branches: [ main ]

jobs:
  create_environment:
    runs-on: ubuntu-latest
  
    steps:
      # checkout base repository
      - id: checkout-repo
        uses: actions/checkout@v3
        with:
          ref: main   
      
      # prepare core environment
      - id: load-env
        run: |
          sudo apt-get update
          sudo apt-get install unzip file gringo
          sudo apt-get install build-essential binutils-dev gfortran python-dev python-yaml ca-certificates
      
      # checkout spack to create build environment
      - id: checkout-spack
        uses: actions/checkout@v3
        with:
          repository: uturuncoglu/spack
          path: spack
          ref: hotfix/esmf

      # create build environment
      - id: create-env
        run: |
          . $GITHUB_WORKSPACE/spack/share/spack/setup-env.sh
          spack -e ${{ github.workspace }} concretize -f
          
      # restore build environment from cache
      - id: restore-env
        uses: actions/cache@v2
        with:
          path: ~/.spack-ci
          key: ${{ hashFiles('**/spack.lock') }}
          restore-keys: |
            spack
            
      # create build environment
      - id: install-env
        run: |
          . $GITHUB_WORKSPACE/spack/share/spack/setup-env.sh 
          spack -e ${{ github.workspace }} install -j3
      
      # checkout data models
      - id: checkout-cdeps
        uses: actions/checkout@v3
        with:
          repository: uturuncoglu/CDEPS
          path: cdeps
          ref: hotfix/std_build      
      
      # build data models
      - id: install-cdeps
        run: |
          export PATH=$HOME/.spack-ci/view/bin:$PATH
          export ESMFMKFILE=$HOME/.spack-ci/view/lib/esmf.mk
          echo $ESMFMKFILE
          echo $HOME
          find $HOME/. -name "esmf.mk"
          cat $ESMFMKFILE
          cd cdeps
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install \
            -DPIO_C_LIBRARY=$HOME/.spack-ci/view/lib \
            -DPIO_C_INCLUDE_DIR=$HOME/.spack-ci/view/include \
            -DPIO_Fortran_LIBRARY=$HOME/.spack-ci/view/lib \
            -DPIO_Fortran_INCLUDE_DIR=$HOME/.spack-ci/view/include \
            -DCMAKE_Fortran_FLAGS="-ffree-line-length-none -ffixed-line-length-none" ../
          make
          make install
          
