name: comptest
 
on:
  push:
    branches: [ main ]

jobs:
  create_environment:
    runs-on: ubuntu-latest #ubuntu:18.04
    
    # set custom environment variables
    #env:
    #  # set env and view paths for spack
    #  SPACK_ENV_PATH: "$GITHUB_WORKSPACE/spack/env"
    #  SPACK_ENV_VIEW: "$SPACK_ENV_PATH/view"
    
    steps:
      # checkout base repository
      - id: checkout-repo
        uses: actions/checkout@v3
        with:
          ref: main   
      
      # prepare core environment
      - id: load-env
        run: |
          sudo apt-get update
          sudo apt-get install build-essential binutils-dev gfortran python-dev python-yaml ca-certificates
      
      # checkout spack to create build environment
      - id: checkout-spack
        uses: actions/checkout@v3
        with:
          repository: uturuncoglu/spack
          path: spack
          ref: hotfix/esmf

      # create build environment
      - id: create-env
        run: |
          . $GITHUB_WORKSPACE/spack/share/spack/setup-env.sh
          spack -v solve zlib
          spack env create myenv ${{ github.workspace }}/spack.yaml
          spack env activate myenv
          spack env status
          spack install
          
          
          
