name: comptest
 
on:
  push:
    branches: [ main ]

jobs:
  create_docker_file:
    runs-on: ubuntu-latest #ubuntu:18.04
    steps:
      # prepare core environment
      - id: load-env
        run: |
          sudo apt-get update
          sudo apt-get install build-essential binutils-dev gfortran python-dev python-yaml ca-certificates
      # checkout spack to create build environment
      - id: checkout-spack
        uses: actions/checkout@v3
        with:
          repository: uturuncoglu/spack
          path: spack
          ref: hotfix/esmf
      # create build environment
      - id: create-env
        run: |
          pushd spack
          ls -al ${{ github.workspace }}
          ls -al ../${{ github.workspace }}
          bin/spack env create myenv ${{ github.workspace }}/spack.yaml
          bin/spack env activate --sh myenv
          bin/spack env activate myenv
          
          
          
